### ISSUE TITLE
Compatibility: Sony UMC-R10C

### ISSUE THREAD

**Issue by TSC21** [bosch-ros-pkg/photo#9]
Hello and thanks in advance for your time,

I would like to use this package with a Sony UMC-R10C camera. But before acquiring the HW for a specific purpose, I would like to understand if it would be compatible with ROS through this same package. I checked the `libgphoto2` repository and the seem to have [compatibility](https://github.com/gphoto/libgphoto2/blob/master/camlibs/ptp2/cameras/sony-umc-r10c.txt) with this same camera - so, should I expect it to work as well with this package.

Thank you!

**Comment by TSC21** [comment]
@Karsten1987 is this something you can help answer? Thanks in advance!

**Comment by Karsten1987** [comment]
@TSC21 I am sorry, I believe I can't really answer this question. I don't have the hardware available and wouldn't dare to give you a qualified answer to this. You might want to ask your questions on answers.ros.org or similar platforms.

I am closing this issue here. Feel free to re-open it in case you have a follow up question or even an answer to your question.
